# Cosmos Discord Faucet configuration

verbose        = "yes"

[cosmos]
prefix         = "terp"
denomination   = "uterpx"
feedenom       = "upersyx"

[testnets]
    [testnets.theta]
    node_url = "http://127.0.0.1:26657"
    chain_id = "athena-2"
    faucet_address = "terp1n6tgne5fhfhnhy0eq2r3740xxc3t2txwdg699j"
    block_explorer_tx = "https://explorer.bccnodes.com/terp/tx/"
    daily_cap = "400000000"
    amount_to_send = "10000000"
    tx_fees = "50000"
    
[discord]
bot_token = ""
# comma separated list of channels
channels_to_listen = "faucet"
# how often user can request tokens from faucet (seconds)
# 10800 = 3  hours
# 86400 = 24 hours
request_timeout    = "86400"
